railsTraining/practice1/config/routes.rb
Rails.application.routes.draw do
  get '/admin-login', to: 'admin_authentication#new', as: :admin_login
  post '/admin-login', to: 'admin_authentication#create'
  delete '/admin-logout', to: 'admin_authentication#destroy', as: :admin_logout

  root 'articles#index'
  get '/index.xml', to: 'articles#index'
  resources :articles, path: '/'
end

railsTraining/practice1/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
end

railsTraining/practice1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railsTraining/practice1/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

railsTraining/practice1/app/controllers/admin_authentication_controller.rb
class AdminAuthenticationController < ApplicationController
  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.find_by(username: admin_user_params[:username])
    if @admin_user && @admin_user.password == admin_user_params[:password]
      session[:admin_user_id] = @admin_user.id
      redirect_to root_path
    else
      @admin_user = AdminUser.new(admin_user_params)
      flash.alert = t('flash_messages.login_failure')
      render :new
    end
  end

  def destroy
    session[:admin_user_id] = nil
    redirect_to root_path, notice: t('flash_messages.logout_success')
  end

  private

  def admin_user_params
    params.require(:admin_user).permit(:username, :password)
  end
end

railsTraining/practice1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_admin_user
  helper_method :admin_logged_in?

  private

  def current_admin_user
    AdminUser.find_by(id: session[:admin_user_id])
  end

  def admin_logged_in?
    !current_admin_user.nil?
  end

  def authenticate_admin
    return if admin_logged_in?

    redirect_back fallback_location: root_path,
                  alert: t('flash_messages.authenticate_admin_failure')
  end
end

railsTraining/practice1/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin, except: %i[index show]

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_url(@article),
                  notice: t('flash_messages.create_success', model: Article.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_url(@article),
                  notice: t('flash_messages.update_success', model: Article.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_url,
                notice: t('flash_messages.destroy_success', model: Article.model_name.human)
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

railsTraining/practice1/app/controllers/temporary_controller.rb
class TemporaryController < ApplicationController
  def home
  end
end

railsTraining/practice1/app/helpers/application_helper.rb
module ApplicationHelper
end

railsTraining/practice1/app/views/admin_authentication/new.html.erb
<h1><%= t("admin_login") %></h1>

<%= form_with(model: @admin_user, url: admin_login_path, local: true) do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username %>
  <br />
  <%= form.label :password %>
  <%= form.password_field :password %>

  <div class="actions">
    <%= form.submit t("login") %>
  </div>
<% end %>

railsTraining/practice1/app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id='error_explanation'>
      <h2><%= t('errors_caused_save_failure', error_count: article.errors.count) %></h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= form.label :title %>
    <%= form.text_field :title, size: "63" %>
  </div>

  <div class='field'>
    <%= form.label :content %>
    <%= form.text_area :content,  size: "60x20" %>
  </div>

  <div class='actions'>
    <%= form.submit %>
  </div>
<% end %>

railsTraining/practice1/app/views/articles/edit.html.erb
<h1><%= t('edit_model', model: Article.model_name.human) %></h1>

<%= link_to t('show'), @article %>

<%= render 'form', article: @article %>

<%= link_to t('back'), articles_path %>

railsTraining/practice1/app/views/articles/index.html.erb
<h1>記事</h1>

<% if admin_logged_in? %>
  <p>
    <%= link_to t('create_model', model: Article.model_name.human), new_article_path %>
  </p>
<% end %>

<table>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= t('time_ago', time_ago: time_ago_in_words(article.created_at)) %></td>
        <td><%= link_to article.title, article %></td>
        <% if admin_logged_in? %>
          <td><%= link_to t('edit'), edit_article_path(article) %></td>
          <td><%= link_to t('delete'), article, method: :delete, data: { confirm: t('delete_confirmation') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

railsTraining/practice1/app/views/articles/new.html.erb
<h1><%= t('create_model', model: Article.model_name.human) %></h1>

<%= render 'form', article: @article %>

<%= link_to t('back'), articles_path %>

railsTraining/practice1/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<%= @article.created_at.strftime(t('date_format')) %>

<% if admin_logged_in? %>
  | <%= link_to t('edit'), edit_article_path(@article) %>
  | <%= link_to t('delete'), @article, method: :delete, data: { confirm: t('delete_confirmation') } %>
<% end %>

<p><%= @article.content %></p>

<%= link_to t('back'), articles_path %>

railsTraining/practice1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="top-bar">
      <div>
        <%= link_to t('home'), root_path %>
      </div>
      <div>
        <% if admin_logged_in? %>
          <%= current_admin_user.username %>としてログインしています。
          <%= link_to t('logout'), admin_logout_path, method: :delete, data: { confirm: t("logout_confirmation") } %>
        <% else %>
          <%= link_to t('admin_login'), admin_login_path %>
        <% end %>
      </div>
    </div>

    <div class="content">
      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>
    
      <%= yield %>
    </div>
  </body>
</html>

railsTraining/practice1/app/views/temporary/home.html.erb
<p>This page will be deleted.</p>